import axios from 'axios';
import firebase from 'firebase';
import ReduxSagaFirebase from 'redux-saga-firebase';

const API_TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik9FVTRNRUpGUmtVek4wUXhOa1UwTVVFek1EUXpOVUkwT0RSRk5VTXdRamxFTlRJelFUUTVSQSJ9.eyJpc3MiOiJodHRwczovL3RpdGFuaXVtc29mdC5ldS5hdXRoMC5jb20vIiwic3ViIjoibUdpYkxRYkowRlcyOE5IT0RUSWVaTlRVTEU3QkVCYndAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vdGl0YW5pdW1zb2Z0LmV1LmF1dGgwLmNvbS9hcGkvdjIvIiwiaWF0IjoxNTIyNzYzMzQxLCJleHAiOjE1MjI4NDk3NDEsImF6cCI6Im1HaWJMUWJKMEZXMjhOSE9EVEllWk5UVUxFN0JFQmJ3Iiwic2NvcGUiOiJyZWFkOmNsaWVudF9ncmFudHMgY3JlYXRlOmNsaWVudF9ncmFudHMgZGVsZXRlOmNsaWVudF9ncmFudHMgdXBkYXRlOmNsaWVudF9ncmFudHMgcmVhZDp1c2VycyB1cGRhdGU6dXNlcnMgZGVsZXRlOnVzZXJzIGNyZWF0ZTp1c2VycyByZWFkOnVzZXJzX2FwcF9tZXRhZGF0YSB1cGRhdGU6dXNlcnNfYXBwX21ldGFkYXRhIGRlbGV0ZTp1c2Vyc19hcHBfbWV0YWRhdGEgY3JlYXRlOnVzZXJzX2FwcF9tZXRhZGF0YSBjcmVhdGU6dXNlcl90aWNrZXRzIHJlYWQ6Y2xpZW50cyB1cGRhdGU6Y2xpZW50cyBkZWxldGU6Y2xpZW50cyBjcmVhdGU6Y2xpZW50cyByZWFkOmNsaWVudF9rZXlzIHVwZGF0ZTpjbGllbnRfa2V5cyBkZWxldGU6Y2xpZW50X2tleXMgY3JlYXRlOmNsaWVudF9rZXlzIHJlYWQ6Y29ubmVjdGlvbnMgdXBkYXRlOmNvbm5lY3Rpb25zIGRlbGV0ZTpjb25uZWN0aW9ucyBjcmVhdGU6Y29ubmVjdGlvbnMgcmVhZDpyZXNvdXJjZV9zZXJ2ZXJzIHVwZGF0ZTpyZXNvdXJjZV9zZXJ2ZXJzIGRlbGV0ZTpyZXNvdXJjZV9zZXJ2ZXJzIGNyZWF0ZTpyZXNvdXJjZV9zZXJ2ZXJzIHJlYWQ6ZGV2aWNlX2NyZWRlbnRpYWxzIHVwZGF0ZTpkZXZpY2VfY3JlZGVudGlhbHMgZGVsZXRlOmRldmljZV9jcmVkZW50aWFscyBjcmVhdGU6ZGV2aWNlX2NyZWRlbnRpYWxzIHJlYWQ6cnVsZXMgdXBkYXRlOnJ1bGVzIGRlbGV0ZTpydWxlcyBjcmVhdGU6cnVsZXMgcmVhZDpydWxlc19jb25maWdzIHVwZGF0ZTpydWxlc19jb25maWdzIGRlbGV0ZTpydWxlc19jb25maWdzIHJlYWQ6ZW1haWxfcHJvdmlkZXIgdXBkYXRlOmVtYWlsX3Byb3ZpZGVyIGRlbGV0ZTplbWFpbF9wcm92aWRlciBjcmVhdGU6ZW1haWxfcHJvdmlkZXIgYmxhY2tsaXN0OnRva2VucyByZWFkOnN0YXRzIHJlYWQ6dGVuYW50X3NldHRpbmdzIHVwZGF0ZTp0ZW5hbnRfc2V0dGluZ3MgcmVhZDpsb2dzIHJlYWQ6c2hpZWxkcyBjcmVhdGU6c2hpZWxkcyBkZWxldGU6c2hpZWxkcyB1cGRhdGU6dHJpZ2dlcnMgcmVhZDp0cmlnZ2VycyByZWFkOmdyYW50cyBkZWxldGU6Z3JhbnRzIHJlYWQ6Z3VhcmRpYW5fZmFjdG9ycyB1cGRhdGU6Z3VhcmRpYW5fZmFjdG9ycyByZWFkOmd1YXJkaWFuX2Vucm9sbG1lbnRzIGRlbGV0ZTpndWFyZGlhbl9lbnJvbGxtZW50cyBjcmVhdGU6Z3VhcmRpYW5fZW5yb2xsbWVudF90aWNrZXRzIHJlYWQ6dXNlcl9pZHBfdG9rZW5zIGNyZWF0ZTpwYXNzd29yZHNfY2hlY2tpbmdfam9iIGRlbGV0ZTpwYXNzd29yZHNfY2hlY2tpbmdfam9iIHJlYWQ6Y3VzdG9tX2RvbWFpbnMgZGVsZXRlOmN1c3RvbV9kb21haW5zIGNyZWF0ZTpjdXN0b21fZG9tYWlucyByZWFkOmVtYWlsX3RlbXBsYXRlcyBjcmVhdGU6ZW1haWxfdGVtcGxhdGVzIHVwZGF0ZTplbWFpbF90ZW1wbGF0ZXMiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.N2Mb_7mOSu6bmyCNq_TQfSCXX4SPbOMyZfFUIQsv9pP6qbrj9cVuQ92KLVngY7PiOTughU5WkJNk8B0EQEeG_pO9hjJfIxHanVJnZ0L-OeYoVohXcInA5WxPbeOf-3cyQrOEj1MdfvB4Huy_eLV4J1IJNjiK5ncQI0oFnjdEyva0BgPsGuX2ZoNvABuc_Jp_WMIREu4JyM5MqAN9ta0zHCLaKRRHLR6nyddYzG2mCn8CZtQdZbswFgH-qjBAcQvE9vLpIwimn3H6g_9I0LSrg6Wk3XOAYbcrraTy82hHZfYYptaA8VCJdDyK7EKcCo_-1svfVaXU1fCXN4jRf8xz6g';
const BASE_URL = 'https://foodblog-4859b.firebaseio.com/node';
const DATABASE_SECRET = 'LioBOBggnzDQZntQWi7XRsuYKXEMRC8YIQpU1UMl';

export function getUsersData() {
  const url = `${BASE_URL}/users.json?auth=${DATABASE_SECRET}`;
  return axios.get(url).then(response => response.data);
}

export function getEventsData() {
  const url = `${BASE_URL}/events.json?auth=${DATABASE_SECRET}`;
  return axios.get(url).then(response => response.data);
}

export function getPostsData() {
  const url = `${BASE_URL}/posts.json?auth=${DATABASE_SECRET}`;
  return axios.get(url).then(response => response.data);
}

export function getUsersList() {
  const url = 'https://titaniumsoft.eu.auth0.com/api/v2/users';
  return axios.get(url, { headers: { Authorization: `bearer ${API_TOKEN}` } }).then(response => response);
}

// firebase settings
const config = {
  apiKey: 'AIzaSyAYhQNgycDJ_-Oru2EaAUc_j9oVFKk2ArI',
  authDomain: 'foodblog-4859b.firebaseapp.com',
  databaseURL: 'https://foodblog-4859b.firebaseio.com',
};

const app = firebase.initializeApp(config);
export const reduxSagaFirebase = new ReduxSagaFirebase(app);

